### PR TITLE
Fix emails getting exposed in `To:`-field

### PR DESCRIPTION
**Pull request by SindreKjelsrud**
> _Closes #111_

I think this should fix the emails getting exposed :sweat_smile:

**NB!** Should probably change the mail to something else, I don't know if it's correct.

### CODE REVIEW

**Review by aslakhol — CHANGES_REQUESTED** [review]
Thanks a bunch for the PR! 

Changing to `bcc` is a fine temporary measure. In the future I would like to rework the emails so that I send individual emails to each email, rather than one big one with a lot of emails in the too field. That just seems more professional. 

However, I would accept a PR with the fix of just changing to `bcc` (and I'll set up a no-reply email so that works fine). But, this isn't the right place to do it. The email you've changed is the email for the login-code, which only goes to one recipient so it doesn't need the `bcc` treatment. 

If you search for `to: emails` and `to: attendeeEmails` you should find all the right spots. There are quite a few different emails that we send to a bunch of people. 

If that seems like a bigger bite than you where ready to take that's totally OK, thanks for pointing out the problem. Just let me know and I'll try and get the fix done myself ^^

**Comment by aslakhol** [comment]
Of course, if you feel up for making the change to sending individual emails with the `to` field I'm very open to a PR on this as well. And I'll be available for support if you want it ^^

**Comment by SindreKjelsrud** [comment]
Think I've done it right now :sweat_smile: Did the temporary measure with `bcc` as of now!

**Review by aslakhol — APPROVED** [review]
Looks good, thanks for the PR!

**Pull request merged**
